console.log("This is the start of the program");
try{
    console.log(a);
}
catch(err){
    console.log("The Error is: "+err);
}
console.log("This is the end of the program");